### ISSUE TITLE
[TOKEN] listing

### ISSUE THREAD

**Issue by sadhellkill** [blazeswap/default-lists#13]
## Token's name and symbol

- name: PepeSGBToken
- symbol: PEPES

## Token's website

https://pepez.pw/

## Explorer link

- https://songbird-explorer.flare.network/token/0x5D463b081184b00Fc8f35dA07E7b726ED17531a4/token-transfers

## Token's contract address

- 0x5D463b081184b00Fc8f35dA07E7b726ED17531a4

## PR checklist

- [x] The token has a website
- [x] The token has a contract address on the chain you want to be added
- [x] The smart contract does not allow the minting of an arbitrary amount of tokens (either the minting rules are coded in the smart contract, or the minting permission has been released)
- [x] Logo is provided
  - [x] The logo's shape is enclosed in a circle
  - [x] The logo has a height 500px and a width 500px
  - [x] The logo has 8px padding around it

**Comment by sadhellkill** [comment]
Hi guys! let me know if its all good to add?

**Comment by sadhellkill** [comment]
![token png](https://github.com/blazeswap/default-lists/assets/35455679/cb28ea8c-3fd2-4181-9699-46a5c94bad9e)

**Comment by alexdupre** [comment]
Token added!
