### ISSUE TITLE
[FLX] listing

### ISSUE THREAD

**Issue by AlexRodX** [blazeswap/default-lists#24]
## Token's name and symbol

- name: [FlareFox]
- symbol: [FLX]

## Token's website

- [https://flarefoxinu.xyz/]

## Explorer link

- [https://flare-explorer.flare.network/address/0x22757fb83836e3F9F0F353126cACD3B1Dc82a387]

## Token's contract address

- [0x22757fb83836e3F9F0F353126cACD3B1Dc82a387]

## Token Logo
![flare_fox_logo](https://github.com/blazeswap/default-lists/assets/155815283/35e09fb8-37b0-4889-8e10-9601315ac3f6)

## PR checklist

- [x] The token has a website
- [x] The token has a contract address on the chain you want to be added
- [x] The smart contract does not allow the minting of an arbitrary amount of tokens (either the minting rules are coded in the smart contract, or the minting permission has been released)
- [x] Logo is provided
  - [x] The logo's shape is enclosed in a circle
  - [x] The logo has a height 500px and a width 500px
  - [x] The logo has 8px padding around it

**Comment by OctoD** [comment]
May I would ask you to provide a higher resolution logo (it should be 500px * 500px, the one provided is just 136*136).

Thank you!
