### ISSUE TITLE
[FINU] listing

### ISSUE THREAD

**Issue by flareinu** [blazeswap/default-lists#33]
## Token's name and symbol

- name: Flare Inu
- symbol: FINU

## Token's website

- https://flareinu.com/

## Explorer link

- https://flare-explorer.flare.network/token/0x282b88514A52FcAdCD92b742745398f3574697d4/token-transfers

## Token's contract address

- 0x282b88514A52FcAdCD92b742745398f3574697d4

## PR checklist

- https://flareinu.com/ - The token has a website
- 0x282b88514A52FcAdCD92b742745398f3574697d4 - The token has a contract address on the chain you want to be added
- https://finu.slite.page/p/s0TK4FsmUf9ccy/Token-Contracts - The smart contract does not allow the minting of an arbitrary amount of tokens (either the minting rules are coded in the smart contract, or the minting permission has been released)
- https://drive.google.com/file/d/1BD49ZXjplnO7UZ8HWEUwUYMTq78gMb2d/view - Logo is provided
  - https://drive.google.com/drive/folders/1qtBGQIRGro8HcGxIdLC8KJ_YlO-cFCWe?usp=drive_link - The logo's shape is enclosed in a circle
  - https://drive.google.com/drive/folders/1qtBGQIRGro8HcGxIdLC8KJ_YlO-cFCWe?usp=drive_link - The logo has a height 500px and a width 500px
  - https://drive.google.com/drive/folders/1qtBGQIRGro8HcGxIdLC8KJ_YlO-cFCWe?usp=drive_link - The logo has 8px padding around it

**Comment by flareinu** [comment]
I look forward to your kind review of my application! Thank you! ☀️

**Comment by alexdupre** [comment]
You should verify your contract on at least one of the Flare's explorers (Blockscout or Flarescan)

**Comment by flareinu** [comment]
Done, contract is verified in Flarescan now: https://flarescan.com/address/0x282b88514A52FcAdCD92b742745398f3574697d4/contract/14/code
