### ISSUE TITLE
[TOKEN] listing

### ISSUE THREAD

**Issue by snooopytoken** [blazeswap/default-lists#5]
## Token's name and symbol

- name: Snooopy
- symbol: SNOOOPY

## Token's website

- https://snooopytoken.com

## Explorer link

- https://flare-explorer.flare.network/address/0xA620ef71cAf4A4E93A096d324E40866e381F1E57

## Token's contract address

- 0xA620ef71cAf4A4E93A096d324E40866e381F1E57

## PR checklist

- [x] The token has a website
- [x] The token has a contract address on the chain you want to be added
- [x] The smart contract does not allow the minting of an arbitrary amount of tokens (either the minting rules are coded in the smart contract, or the minting permission has been released)
- [x] Logo is provided
  - [x] The logo's shape is enclosed in a circle
  - [x] The logo has a height 500px and a width 500px
  - [x] The logo has 8px padding around it
![SNOOOPY](https://user-images.githubusercontent.com/128030515/225574843-98787556-8aa5-4ad0-baf9-227210e584e0.png)

**Comment by OctoD** [comment]
Merged, thank you and welcome aboard!

**Comment by FlareSwap** [comment]
Guys could you remove Snooopy token from your DEX ? It was just an experiment and I can't let people to put their money into an useless token. Thank you.

**Comment by snooopytoken** [comment]
And here I confirm the removal request from the original github account. Thanks.
