### ISSUE TITLE
[TOKEN] listing

### ISSUE THREAD

**Issue by FlareXGods** [blazeswap/default-lists#8]
## Token's name and symbol

- name: [GFlare]
- symbol: [GFLR]

## Token's website

- [https://flaregods.xyz]

## Explorer link

- (https://flare-explorer.flare.network/address/0x90e157A979074f9f2fe8B124Ba08e6F72dc812FC/contracts

## Token's contract address

- 0x90e157A979074f9f2fe8B124Ba08e6F72dc812FC

## PR checklist

- [yes ] The token has a website
- [ yes] The token has a contract address on the chain you want to be added
- [yes] The smart contract does not allow the minting of an arbitrary amount of tokens (either the minting rules are coded in the smart contract, or the minting permission has been released)
- [ yes] Logo is provided
  - [yes ] The logo's shape is enclosed in a circle
  - [ yes] The logo has a height 500px and a width 500px
  - [ yes] The logo has 8px padding around it

**Comment by alexdupre** [comment]
Adding a token to the default list has an impact for all users, so before we take such decision we need to see that it's actually used by hundreds of people and has good liquidity on the DEX with multiple liquidity providers. I don't see the uploaded logo, either. Nevertheless, in the meanwhile you can facilitate the trading on BlazeSwap by providing pre-determined URLs, like https://app.blazeswap.xyz/swap/?outputCurrency=0x90e157A979074f9f2fe8B124Ba08e6F72dc812FC or https://app.blazeswap.xyz/pool/add/?tokenA=0x1D80c49BbBCd1C0911346656B529DF9E5c2F783d&tokenB=0x90e157A979074f9f2fe8B124Ba08e6F72dc812FC

**Comment by FlareXGods** [comment]
Hi There, we do have liquidity on it and also people have added LP. i couldnt upload logo for some reason..i have sent you via twitter instead

**Comment by FlareXGods** [comment]
there alot over 100 holders and also we have added more liquidity today! please let me know if its all good to be listed
